final List<String> daftarKampus = [
  'Institut Pertanian Bogor (IPB University)',
  'Institut Sains Dan Teknologi Nasional (ISTN)',
  'Institut Teknologi Bandung (ITB)',
  'Institut Teknologi Sepuluh Nopember (ITS)',
  'Institut Teknologi Telkom Surabaya (ITTS)',
  'Institut Pemerintahan Dalam Negeri (IPDN)',
  'Politeknik Elektronika Negeri Surabaya (PENS)',
  'Politeknik Keuangan Negara STAN (PKN STAN)',
  'Politeknik Negeri Jakarta (PNJ)',
  'Politeknik Statistika STIS (Polstat STIS)',
  'Sekolah Tinggi Ilmu Kesehatan (STIKES)',
  'Sekolah Tinggi Intelijen Negara (STIN)',
  'Sekolah Tinggi Meteorologi, Klimatologi, dan Geofisika (STMKG)',
  'Sekolah Tinggi Pariwisata Bandung (STPB)',
  'Universitas Airlangga (UNAIR)',
  'Universitas Atma Jaya Yogyakarta (UAJY)',
  'Universitas Bina Nusantara (BINUS)',
  'Universitas Brawijaya (UB)',
  'Universitas Diponegoro (UNDIP)',
  'Universitas Gadjah Mada (UGM)',
  'Universitas Hasanuddin (UNHAS)',
  'Universitas Indonesia (UI)',
  'Universitas Kristen Krida Wacana (UKRIDA)',
  'Universitas Muhammadiyah Prof. Dr. HAMKA (UHAMKA)',
  'Universitas Negeri Jakarta (UNJ)',
  'Universitas Padjadjaran (UNPAD)',
  'Universitas Pelita Harapan (UPH)',
  'Universitas Sebelas Maret (UNS)',
  'Universitas Trisakti',
];
